name: mosquitto
services:
    eclipse-mosquitto:
        ports:
            - 1883:1883
            - 9001:9001
        volumes:
            - ./mosquitto:/mosquitto/
        image: eclipse-mosquitto:2.0.18
